In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from pandas_ml import ConfusionMatrix
from sklearn import model_selection
actuals=[]
probs=[]
hats=[]

In [44]:
Data = pd.read_csv('winequality-red.csv')

In [45]:
Xset, Yset = Data.iloc[:,:-1], Data.iloc[:, -1]

In [46]:
from sklearn.model_selection import train_test_split
Xset_train, Xset_test, Yset_train, Yset_test = train_test_split(Xset, Yset, test_size=0.30, random_state=42)
modelnow = GaussianNB()
modelnow.fit(Xset,Yset)

GaussianNB(priors=None)

In [47]:
#help(GaussianNB(priors=None))
foldhats = modelnow.predict(Xset)
print(foldhats)

[5 5 5 ... 6 5 6]


In [48]:
#print ("Crossvalidation Error")
#print ("CVerror = ", metrics.accuracy_score(actuals,hats))
#print (metrics.classification_report(actuals, hats))

In [49]:
foldprobs = modelnow.predict_proba(Xset)[:,1]
print(foldprobs)


[0.07310912 0.02355739 0.02618504 ... 0.00640836 0.01824814 0.00299363]


In [50]:
actuals = np.append(actuals, Yset)
print(actuals)

[5. 5. 5. ... 6. 5. 6.]


In [71]:
print("Generalization Error  = " , accuracy_score(actuals, foldhats))


Generalization Error  =  0.5647279549718575


In [54]:
from sklearn.model_selection import train_test_split
Xset_train, Xset_test, Yset_train, Yset_test = train_test_split(Xset, Yset, test_size=0.20, random_state=42)


In [55]:
modelnow1 = GaussianNB()
modelnow1.fit(Xset_train,Yset_train)

GaussianNB(priors=None)

In [57]:
foldhats1 = modelnow.predict(Xset_test)
print(foldhats1)

[5 5 6 5 6 5 5 5 6 6 7 5 6 5 5 7 5 6 7 5 5 5 6 6 5 6 7 6 5 7 5 6 6 5 5 5 7
 6 6 6 6 5 7 5 6 6 7 6 5 6 5 4 6 6 5 5 6 6 6 5 5 6 6 5 7 6 7 5 7 5 7 5 6 6
 6 5 7 5 6 7 6 7 5 6 6 7 5 6 7 5 6 5 6 7 5 6 5 6 5 5 5 5 6 6 5 6 6 5 6 5 8
 5 5 5 6 7 6 6 5 6 6 5 6 5 5 5 6 6 6 6 6 5 5 7 6 5 5 5 5 6 7 6 6 6 6 5 6 5
 6 5 6 6 5 6 6 6 5 6 5 6 7 5 6 5 5 6 5 5 5 5 5 5 7 5 5 6 7 5 5 4 5 7 5 7 5
 7 4 6 7 5 5 7 6 7 6 5 5 5 6 6 5 5 6 5 7 6 5 6 6 7 6 5 6 7 7 6 4 5 6 5 5 7
 7 6 4 5 5 7 5 6 5 5 7 6 7 6 5 6 5 5 6 5 6 7 4 6 6 5 7 5 6 6 5 5 3 5 5 6 6
 8 7 6 5 7 6 7 5 5 7 7 5 6 5 5 6 6 5 7 7 5 7 5 5 5 5 6 5 6 5 4 5 8 8 5 5 7
 5 7 6 7 6 5 6 5 5 5 6 6 6 7 6 6 5 6 5 6 5 5 6 5]


In [59]:
actuals1=[]
actuals1 = np.append(actuals1,Yset_test)
print(actuals1)

[6. 5. 6. 5. 6. 5. 5. 5. 5. 6. 7. 3. 5. 5. 6. 7. 5. 7. 8. 5. 5. 6. 5. 6.
 6. 6. 7. 6. 5. 6. 5. 5. 6. 5. 6. 5. 7. 5. 4. 6. 5. 5. 7. 5. 5. 6. 7. 6.
 5. 6. 5. 5. 5. 7. 6. 6. 6. 5. 5. 5. 5. 7. 5. 6. 6. 5. 6. 5. 6. 5. 6. 4.
 6. 6. 6. 5. 8. 5. 6. 6. 5. 6. 5. 6. 6. 7. 5. 6. 7. 4. 7. 6. 5. 5. 5. 6.
 5. 6. 5. 6. 5. 5. 5. 7. 6. 7. 6. 5. 6. 5. 8. 5. 6. 5. 6. 7. 6. 6. 5. 6.
 6. 6. 6. 6. 6. 6. 7. 6. 5. 5. 6. 5. 5. 5. 6. 5. 5. 5. 5. 6. 7. 6. 8. 5.
 5. 5. 6. 6. 6. 5. 6. 7. 6. 5. 6. 5. 5. 6. 6. 6. 7. 5. 7. 5. 5. 5. 6. 6.
 5. 5. 6. 5. 7. 6. 7. 6. 6. 5. 5. 6. 4. 6. 5. 7. 5. 5. 4. 5. 7. 6. 5. 6.
 6. 7. 6. 5. 5. 6. 5. 7. 5. 6. 6. 5. 7. 5. 5. 5. 6. 7. 7. 5. 5. 6. 6. 7.
 6. 5. 6. 6. 6. 6. 6. 7. 4. 5. 5. 7. 5. 5. 5. 5. 6. 6. 5. 7. 5. 6. 6. 6.
 5. 4. 6. 7. 6. 7. 5. 6. 6. 5. 5. 6. 5. 6. 4. 5. 6. 6. 5. 6. 6. 5. 5. 6.
 7. 7. 6. 5. 6. 6. 5. 6. 5. 6. 5. 5. 5. 6. 6. 6. 7. 5. 5. 6. 5. 7. 5. 6.
 4. 6. 6. 8. 6. 5. 5. 6. 5. 7. 6. 6. 5. 5. 7. 6. 6. 5. 6. 6. 5. 7. 6. 6.
 6. 6. 5. 6. 5. 5. 6. 4.]


In [70]:
print("Generalization Error  = " , accuracy_score(actuals1, foldhats1))


Generalization Error  =  0.55


In [73]:
actuals2 = []
probs2 = []
hats2 = []
seed = 719
kfold = model_selection.KFold(n_splits=5, shuffle=True, random_state=seed)
for train, test in kfold.split(Xset, Yset):
    #print('train: %s, test: %s' % (train, test))
    # Train classifier on training data, predict test data
    modelnow.fit(Xset[train], Yset[train])foldhats2 = modelnow.predict(Xset[test])
    foldprobs2 = modelnow.predict_proba(Xset[test])[:,1] # Class probability estimates for ROC curve
    actuals2 = np.append(actuals2, Yset[test]) #Combine targets, then probs, and then predictions from each fold
    probs2 = np.append(probs2, foldprobs2)
    hats2 = np.append(hats2, foldhats2)
    

KeyError: '[   0    1    3 ... 1596 1597 1598] not in index'